# Generated by Django 5.2.5 on 2025-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('bed_number', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_location', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('accomodation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('separable', models.CharField(blank=True, max_length=100, null=True)),
                ('wave', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('room_utilization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_type', models.CharField(blank=True, max_length=100, null=True)),
                ('current_type', models.CharField(blank=True, max_length=100, null=True)),
                ('occupancy_status', models.CharField(blank=True, max_length=100, null=True)),
                ('room_physical_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
