# Generated by Django 5.2.5 on 2025-09-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='accomodation_type',
            field=models.CharField(blank=True, choices=[('A (1 * 1)', 'A (1 * 1)'), ('B (1 * 1)', 'B (1 * 1)'), ('C (2 * 1)', 'C (2 * 1)'), ('D (4 * 1)', 'D (4 * 1)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='actual_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.CharField(blank=True, choices=[('NA1', 'NA1'), ('NB1', 'NB1'), ('NB2', 'NB2'), ('CA1', 'CA1'), ('CA2', 'CA2'), ('CB1', 'CB1'), ('CB2', 'CB2'), ('CB3', 'CB3'), ('CB4', 'CB4'), ('CB5', 'CB5'), ('CB6', 'CB6'), ('CB7', 'CB7'), ('CC1', 'CC1'), ('CC2', 'CC2'), ('CC3', 'CC3'), ('CC4', 'CC4'), ('CD1', 'CD1'), ('CD2', 'CD2'), ('CD3', 'CD3'), ('CD4', 'CD4'), ('CD5', 'CD5'), ('CD6', 'CD6'), ('FMA1', 'FMA1'), ('FMB1', 'FMB1'), ('FMC1', 'FMC1'), ('FMD1', 'FMD1')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bed_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='block',
            field=models.CharField(blank=True, choices=[('Blk1', 'Blk1'), ('Blk2', 'Blk2'), ('Blk3', 'Blk3'), ('Blk4', 'Blk4'), ('Blk5', 'Blk5'), ('Blk6', 'Blk6'), ('Blk7', 'Blk7'), ('Blk8', 'Blk8'), ('Blk9', 'Blk9')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.CharField(blank=True, choices=[('Bld1', 'Bld1'), ('Bld2', 'Bld2'), ('Bld3', 'Bld3'), ('Bld4', 'Bld4')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='current_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.CharField(blank=True, choices=[('GF', 'GF'), ('FF', 'FF'), ('SF', 'SF')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='occupancy_status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Hold', 'Hold'), ('Occupied', 'Occupied'), ('Out of Order', 'Out of Order'), ('To be Received', 'To be Received'), ('Vacant Dirty', 'Vacant Dirty'), ('Vacant Ready', 'Vacant Ready')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='room_physical_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='room_utilization_type',
            field=models.CharField(blank=True, choices=[('Commercial', 'Commercial'), ('Non-Commercial (DBFOM)', 'Non-Commercial (DBFOM)'), ('Non-Commercial (FM)', 'Non-Commercial (FM)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='separable',
            field=models.CharField(blank=True, choices=[('SP1', 'SP1'), ('SP2', 'SP2'), ('SP3', 'SP3'), ('SP4', 'SP4'), ('SP5', 'SP5')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='wave',
            field=models.CharField(blank=True, choices=[('Wave 1', 'Wave 1'), ('Wave 2', 'Wave 2'), ('Wave 3', 'Wave 3'), ('Wave 4', 'Wave 4'), ('Wave 5', 'Wave 5'), ('Wave 6', 'Wave 6'), ('Wave 7', 'Wave 7'), ('Wave 8', 'Wave 8'), ('Wave 9', 'Wave 9'), ('Wave 10', 'Wave 10'), ('Wave 11', 'Wave 11'), ('Wave 12', 'Wave 12'), ('Wave 13', 'Wave 13'), ('Wave 14', 'Wave 14'), ('Wave 15', 'Wave 15'), ('Wave 16', 'Wave 16'), ('Wave 17', 'Wave 17'), ('Wave 18', 'Wave 18'), ('Wave 19', 'Wave 19'), ('FM Wave 1', 'FM Wave 1'), ('FM Wave 2', 'FM Wave 2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='zone',
            field=models.CharField(blank=True, choices=[('NZ', 'NZ'), ('CZ', 'CZ'), ('FZ', 'FZ')], max_length=100, null=True),
        ),
    ]
