# Generated by Django 5.2.5 on 2025-09-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0002_alter_unit_accomodation_type_alter_unit_actual_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_location',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
