# Generated by Django 5.2.5 on 2025-10-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0003_alter_unit_unit_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Group Name')),
            ],
            options={
                'verbose_name': 'Company Group',
                'verbose_name_plural': 'Company Groups',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_details', models.TextField(blank=True, verbose_name='Company Details')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='CR Number')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number')),
                ('address_text', models.TextField(blank=True, verbose_name='Address')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Name')),
                ('email_address', models.EmailField(blank=True, max_length=255, verbose_name='Email Address')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('company_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Housing.companygroup', verbose_name='Company Group')),
            ],
            options={
                'verbose_name': 'User Company',
                'verbose_name_plural': 'User Companies',
            },
        ),
    ]
