# Generated by Django 5.2.5 on 2025-11-19 10:19

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0005_housinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housinguser',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_company', to='Housing.usercompany'),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='government_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_group', to='Housing.usercompany'),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='neom_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'Muslim'), ('Non Muslim', 'Non Muslim')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
