# Generated by Django 5.2.5 on 2025-11-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0006_remove_housinguser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'ordering': ['company_group'], 'verbose_name': 'User Company', 'verbose_name_plural': 'User Companies'},
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_group', to='Housing.companygroup'),
        ),
    ]
