# Generated by Django 5.2.5 on 2025-12-22 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def cleanup_audit_fields(apps, schema_editor):
    """Set audit fields to NULL to clear invalid string references"""
    UserCompany = apps.get_model('Housing', 'UserCompany')
    CompanyGroup = apps.get_model('Housing', 'CompanyGroup')
    Unit = apps.get_model('Housing', 'Unit')
    
    UserCompany.objects.all().update(created_by=None, modified_by=None)
    CompanyGroup.objects.all().update(created_by=None, modified_by=None)
    Unit.objects.all().update(created_by=None, modified_by=None)


def reverse_cleanup(apps, schema_editor):
    """Reverse operation - no-op for this cleanup"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Housing', '0007_alter_usercompany_options_alter_housinguser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinguser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_housingusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='housinguser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='housinguser',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_housingusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='housinguser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(cleanup_audit_fields, reverse_cleanup),
    ]
