# Generated by Django 5.2.5 on 2025-12-23 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0009_alter_companygroup_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('intended_checkin_date', models.DateField()),
                ('intended_checkout_date', models.DateField()),
                ('intended_stay_duration', models.IntegerField(blank=True, help_text='Duration in months', null=True)),
                ('occupancy_status', models.CharField(choices=[('Reserved', 'Reserved'), ('Assigned', 'Assigned'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Reserved', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('housing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Housing.housinguser')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckInCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('actual_checkin_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_checkout_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_stay_duration', models.IntegerField(blank=True, help_text='Duration in days', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='Housing.reservation')),
            ],
            options={
                'verbose_name': 'Check-In/Check-Out',
                'verbose_name_plural': 'Check-Ins/Check-Outs',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UnitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('allocation_type', models.CharField(choices=[('Company', 'Company'), ('UUA', 'UUA')], max_length=20)),
                ('uua_number', models.CharField(max_length=50, unique=True, verbose_name='UUA Number')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('a_rooms_beds', models.CharField(blank=True, max_length=20, verbose_name='A (Rooms/Beds)')),
                ('b_rooms_beds', models.CharField(blank=True, max_length=20, verbose_name='B (Rooms/Beds)')),
                ('c_rooms_beds', models.CharField(blank=True, max_length=20, verbose_name='C (Rooms/Beds)')),
                ('d_rooms_beds', models.CharField(blank=True, max_length=20, verbose_name='D (Rooms/Beds)')),
                ('total_rooms_beds', models.CharField(blank=True, max_length=20, verbose_name='Total (Rooms/Beds)')),
                ('allocation_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Revised', 'Revised'), ('Extended', 'Extended'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='Housing.usercompany')),
                ('company_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='Housing.companygroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit Allocation',
                'verbose_name_plural': 'Unit Allocations',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('accommodation_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='Housing.unitallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Housing.unit')),
            ],
            options={
                'verbose_name': 'Unit Assignment',
                'verbose_name_plural': 'Unit Assignments',
                'ordering': ['-created_date'],
                'unique_together': {('allocation', 'unit', 'accommodation_type')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Housing.unitassignment'),
        ),
    ]
