# Generated by Django 5.2.5 on 2025-12-23 11:48

from django.db import migrations


def update_assigned_units(apps, schema_editor):
    """Update occupancy_status to 'Assigned' for all units in unit_assigning table"""
    UnitAssignment = apps.get_model('Housing', 'UnitAssignment')
    Unit = apps.get_model('Housing', 'Unit')
    
    # Get all unit IDs from assignments
    assigned_unit_ids = UnitAssignment.objects.values_list('unit_id', flat=True).distinct()
    
    # Update all those units to 'Assigned'
    updated_count = Unit.objects.filter(id__in=assigned_unit_ids).update(occupancy_status='Assigned')
    
    print(f"Updated {updated_count} units to 'Assigned' status")


def reverse_update(apps, schema_editor):
    """Reverse the migration - set back to Vacant Ready"""
    UnitAssignment = apps.get_model('Housing', 'UnitAssignment')
    Unit = apps.get_model('Housing', 'Unit')
    
    # Get all unit IDs from assignments
    assigned_unit_ids = UnitAssignment.objects.values_list('unit_id', flat=True).distinct()
    
    # Set them back to Vacant Ready
    Unit.objects.filter(id__in=assigned_unit_ids).update(occupancy_status='Vacant Ready')


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0010_reservation_checkincheckout_unitallocation_and_more'),
    ]

    operations = [
        migrations.RunPython(update_assigned_units, reverse_update),
    ]
