# Generated by Django 5.2.5 on 2025-12-23 12:44

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0011_update_assigned_units_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='accomodation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='allocation_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='Housing.usercompany'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='Housing.companygroup'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='govt_id_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='neom_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='Housing.unit'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unit_location_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uua_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='intended_stay_duration',
            field=models.IntegerField(blank=True, help_text='Duration in days', null=True),
        ),
        migrations.AlterField(
            model_name='unitallocation',
            name='allocation_type',
            field=models.CharField(choices=[('UUA', 'UUA'), ('Non UUA', 'Non UUA')], max_length=20),
        ),
    ]
