# Generated by Django 5.2.5 on 2025-12-24 05:48

from django.db import migrations


def update_units_from_reservations(apps, schema_editor):
    """Update units occupancy status based on existing reservations"""
    Reservation = apps.get_model('Housing', 'Reservation')
    Unit = apps.get_model('Housing', 'Unit')
    
    # Get all active reservations with Reserved or Hold status
    active_reservations = Reservation.objects.filter(
        occupancy_status__in=['Reserved', 'Hold']
    ).values_list('unit_id', 'occupancy_status')
    
    updated_count = 0
    for unit_id, status in active_reservations:
        if unit_id:
            Unit.objects.filter(id=unit_id).update(occupancy_status=status)
            updated_count += 1
    
    print(f"Updated {updated_count} units based on existing reservations")


def reverse_update(apps, schema_editor):
    """Reverse the update - set units back to Assigned"""
    Reservation = apps.get_model('Housing', 'Reservation')
    Unit = apps.get_model('Housing', 'Unit')
    
    # Get all units that were updated
    active_reservations = Reservation.objects.filter(
        occupancy_status__in=['Reserved', 'Hold']
    ).values_list('unit_id', flat=True)
    
    Unit.objects.filter(id__in=active_reservations).update(occupancy_status='Assigned')


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0012_reservation_accomodation_type_and_more'),
    ]

    operations = [
        migrations.RunPython(update_units_from_reservations, reverse_update),
    ]
