# Generated by Django 5.2.5 on 2025-12-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0013_update_units_from_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincheckout',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occupancy_status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Hold', 'Hold'), ('Assigned', 'Assigned'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Reserved', max_length=20),
        ),
    ]
