# Generated by Django 5.2.5 on 2025-12-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0014_checkincheckout_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='occupancy_status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Hold', 'Hold'), ('Assigned', 'Assigned'), ('Occupied', 'Occupied'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Reserved', max_length=20),
        ),
    ]
