# Generated by Django 5.2.5 on 2025-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(choices=[('NRC9', 'NRC9'), ('NRC5', 'NRC5')], max_length=50, unique=True),
        ),
    ]
