# Generated by Django 5.2.5 on 2025-09-09 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0002_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
