# Generated by Django 5.2.5 on 2025-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0003_cash_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='submitted_date',
            field=models.DateField(),
        ),
    ]
