# Generated by Django 5.2.5 on 2025-09-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0004_alter_cash_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='activity',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('submitted', 'Submitted to HQ'), ('received', 'Replenishment from HQ')], max_length=20),
        ),
    ]
