# Generated by Django 5.2.5 on 2025-09-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0005_alter_balance_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
