# Generated by Django 5.2.5 on 2025-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0006_alter_cash_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='submitted_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
