# Generated by Django 5.2.5 on 2025-09-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0007_alter_cash_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
