# Generated by Django 5.2.5 on 2025-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0008_alter_cash_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
