# Generated by Django 5.2.5 on 2025-12-01 06:39

import HumanResource.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0009_alter_cash_department_alter_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('iqama_number', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=HumanResource.models.employee_photo_path)),
                ('photo_url', models.URLField(blank=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_notice', 'On Notice'), ('exited', 'Exited')], default='active', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
