# Generated by Django 5.2.5 on 2025-12-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0010_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_number',
            new_name='staffid',
        ),
    ]
