# Generated by Django 5.2.5 on 2025-12-07 11:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0011_rename_employee_number_employee_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
