# Generated by Django 5.2.5 on 2025-12-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0012_alter_employee_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
