# Generated by Django 5.2.5 on 2025-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0015_manager_alter_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo_url',
            field=models.FileField(blank=True, null=True, upload_to='staff/documents/'),
        ),
    ]
