# Generated by Django 5.2.5 on 2025-09-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_appaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appaccess',
            name='code',
        ),
    ]
