# Generated by Django 5.2.5 on 2025-12-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_appaccess_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(choices=[(1, 'C-Level (CEO, CFO, etc.)'), (2, 'Director'), (3, 'Manager'), (4, 'Supervisor'), (5, 'Team Lead'), (6, 'Staff'), (7, 'Intern'), (8, 'Consultant')], help_text='Lower number = higher authority')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='organizational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizationallevel'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('humanresource', 'Human Resource'), ('housing', 'Housing'), ('logistics', 'Logistics'), ('procurement', 'Procurement'), ('ict', 'ICT'), ('qhse', 'QHSE'), ('hardservice', 'Hard Service'), ('softservice', 'Soft Service'), ('training', 'Training'), ('utility', 'Utility'), ('warehouse', 'Warehouse'), ('fls', 'FLS'), ('tickets', 'Tickets')], max_length=50)),
                ('feature', models.CharField(help_text="e.g., 'staff', 'petty_cash', 'units'", max_length=100)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('submit', 'Submit')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['app', 'feature', 'action'],
                'unique_together': {('app', 'feature', 'action')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, to='accounts.permission'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.organizationallevel')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.permission')),
            ],
            options={
                'unique_together': {('organizational_level', 'permission')},
            },
        ),
    ]
