# Generated by Django 5.2.5 on 2025-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationallevel_profile_organizational_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationallevel',
            name='level',
            field=models.IntegerField(choices=[(1, 'Project Manager'), (2, 'Operations Manager'), (3, 'Manager'), (4, 'Supervisor'), (5, 'Staff')], help_text='Lower number = higher authority'),
        ),
    ]
