# Generated by Django 5.2.5 on 2025-12-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0014_employee_manager'),
        ('accounts', '0005_alter_organizationallevel_level'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('humanresource', 'Human Resource'), ('housing', 'Housing'), ('logistics', 'Logistics'), ('procurement', 'Procurement'), ('ict', 'ICT'), ('qhse', 'QHSE'), ('hardservice', 'Hard Service'), ('softservice', 'Soft Service'), ('training', 'Training'), ('utility', 'Utility'), ('warehouse', 'Warehouse'), ('fls', 'FLS'), ('tickets', 'Tickets')], max_length=50)),
                ('request_type', models.CharField(choices=[('petty_cash', 'Petty Cash'), ('leave', 'Leave Request'), ('clearance', 'Clearance'), ('work_notice', 'Work Notice'), ('vehicle_request', 'Vehicle Request'), ('purchase_request', 'Purchase Request'), ('maintenance', 'Maintenance Request'), ('housing_allocation', 'Housing Allocation'), ('training_request', 'Training Request'), ('overtime', 'Overtime Request'), ('transfer', 'Transfer Request'), ('hiring', 'Hiring Request'), ('general', 'General Request')], max_length=50)),
                ('department', models.CharField(blank=True, help_text='Leave blank for all departments', max_length=100)),
                ('approval_level', models.IntegerField(choices=[(1, 'Level 1 - Direct Manager'), (2, 'Level 2 - Department Head'), (3, 'Level 3 - Operations Manager'), (4, 'Level 4 - Project Manager'), (5, 'Level 5 - Final Authority')])),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Is this approval level mandatory?')),
                ('can_skip_if_unavailable', models.BooleanField(default=False, help_text='Skip if no approver available')),
                ('auto_approve_after_days', models.IntegerField(blank=True, help_text='Auto-approve if no response after X days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_organizational_level', models.ForeignKey(help_text='Minimum organizational level required to approve at this level', on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationallevel')),
            ],
            options={
                'verbose_name': 'Approval Authority',
                'verbose_name_plural': 'Approval Authorities',
                'ordering': ['app', 'request_type', 'approval_level'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('app', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('request_title', models.CharField(max_length=255)),
                ('request_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requestor_department', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('returned', 'Returned for Revision')], default='draft', max_length=20)),
                ('current_approval_level', models.IntegerField(default=1)),
                ('total_approval_levels', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to='HumanResource.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('delegated', 'Delegated')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='approvals/attachments/')),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('approval_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.approvalauthority')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_approvals', to='HumanResource.employee')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approvals', to='HumanResource.employee')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to='HumanResource.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='accounts.approvalworkflow')),
            ],
            options={
                'ordering': ['workflow', 'approval_level'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('delegated', 'Delegated'), ('escalated', 'Escalated'), ('commented', 'Commented'), ('viewed', 'Viewed')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('approval_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.approvalstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.approvalworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApproverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Primary approver for this authority')),
                ('is_backup', models.BooleanField(default=False, help_text='Backup approver (acts when primary unavailable)')),
                ('delegation_start', models.DateField(blank=True, null=True)),
                ('delegation_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approvers', to='accounts.approvalauthority')),
                ('delegate_to', models.ForeignKey(blank=True, help_text='Temporary delegate while this approver is unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to='HumanResource.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_assignments', to='HumanResource.employee')),
            ],
            options={
                'ordering': ['approval_authority', '-is_primary', 'employee'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['current_status', 'current_approval_level'], name='accounts_ap_current_970b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['requestor', 'current_status'], name='accounts_ap_request_626d92_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['content_type', 'object_id'], name='accounts_ap_content_64d69d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'approval_level')},
        ),
        migrations.AlterUniqueTogether(
            name='approverassignment',
            unique_together={('employee', 'approval_authority')},
        ),
    ]
