# Generated by Django 5.2.5 on 2026-01-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_approvalauthority_approvalworkflow_approvalstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalauthority',
            name='approval_level',
            field=models.IntegerField(choices=[(1, 'Level 1 - Supervisor'), (2, 'Level 2 - Officer / Engineer'), (3, 'Level 3 - Manager'), (4, 'Level 4 - Operations Manager'), (5, 'Level 5 - Project Manager')]),
        ),
        migrations.AlterField(
            model_name='organizationallevel',
            name='level',
            field=models.IntegerField(choices=[(1, 'Project Manager'), (2, 'Operations Manager'), (3, 'Manager'), (4, 'Officer / Engineer'), (5, 'Supervisor')], help_text='Lower number = higher authority'),
        ),
    ]
