# Generated by Django 5.2.5 on 2025-12-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO Date'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='pr_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='PR No'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.category'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model No'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial No'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT%'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='date',
            field=models.DateField(verbose_name='Receive Date'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='grn_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='GRN No'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='PO No'),
        ),
    ]
