# Generated by Django 5.2.5 on 2025-12-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_receiving_po_date_receiving_pr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitem',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='item_description',
            field=models.TextField(blank=True, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='staff_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Staff ID'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='staff_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dn_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Delivery No'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
