# Generated by Django 5.2.5 on 2025-12-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0003_dispatchitem_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingstockitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.category'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='max_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Max Capacity'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='min_inventory',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min Inventory'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='po_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PO Quantity'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='closingstockitem',
            name='uom',
            field=models.CharField(blank=True, max_length=20, verbose_name='UOM'),
        ),
        migrations.AlterField(
            model_name='closingstockitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Warehouse.location', verbose_name='Storage Location'),
        ),
        migrations.AlterField(
            model_name='closingstockitem',
            name='opening_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='closingstockitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
