# Generated by Django 5.2.5 on 2026-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0004_closingstockitem_category_closingstockitem_item_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='purchase_type',
            field=models.CharField(choices=[('LOCAL', 'Local Purchase'), ('HQ', 'Head Quarters')], default='LOCAL', max_length=20, verbose_name='Purchase Type'),
        ),
    ]
