# Generated by Django 5.2.5 on 2026-01-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_receiving_department_receiving_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivingitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Warehouse.product'),
        ),
    ]
