# Generated by Django 5.2.5 on 2026-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0006_alter_receivingitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingitem',
            name='uom',
            field=models.CharField(blank=True, max_length=50, verbose_name='UOM'),
        ),
    ]
