# Generated by Django 5.2.5 on 2026-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0007_receivingitem_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='department',
            field=models.CharField(blank=True, choices=[('SOFT_SERVICE', 'Soft Service'), ('HARD_SERVICE', 'Hard Service'), ('ICT', 'ICT'), ('FLS', 'FLS')], max_length=20, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='grn_number',
            field=models.CharField(max_length=50, verbose_name='GRN No'),
        ),
    ]
